import { createGlobalTheme } from "@vanilla-extract/css";

export const media = {
  sm: "(min-width: 640px)",
  md: "(min-width: 768px)",
  lg: "(min-width: 1024px)",
  xl: "(min-width: 1280px)",
  "2xl": "(min-width: 1536px)",
  motionSafe: "(prefers-reduced-motion: no-preference)",
  retina: "(-webkit-min-device-pixel-ratio: 2),(min-resolution: 192dpi)",
};

export const tokens = createGlobalTheme(":root", {
  rgb: {
    white: "250, 250, 250",
    black: "46, 46, 46",
    yellow: "241, 234, 71",
    warmRed: "224, 166, 112",
    blue: "34, 101, 199",
    gray: "70, 69, 69",
    cream: "250, 244, 228",
    red: "163, 30, 30",
  },

  font: {
    lsJP: 'LINESeedJP, "Hiragino Kaku Gothic ProN","Hiragino Sans",Meiryo,serif',
    yujiSyuku:
      'Yuji_Syuku_subset, "Hiragino Kaku Gothic ProN","Hiragino Sans",Meiryo,serif',
  },
  fontSize: {
    smallest: "0.694rem",
    sm: "0.833rem",
    initial: "1rem",
    lg: "1.2rem",
    xl: "1.44rem",
    xxl: "1.728rem",
    xxxl: "2.074rem",
    largest: "2.488rem",
  },
  fontWeight: {
    thin: "100",
    extralight: "200",
    light: "300",
    normal: "400",
    medium: "500",
    semibold: "600",
    bold: "700",
    extrabold: "800",
    black: "900",
  },
  lineHeight: {
    none: "1",
    tight: "1.25",
    snug: "1.375",
    normal: "1.5",
    relaxed: "1.85",
    loose: "4",
  },
  letterSpacing: {
    tighter: "-0.05em",
    tight: "-0.025em",
    normal: "0em",
    wide: "0.025em",
    wider: "0.08em",
    widest: "0.12em",
  },
  spacing: {
    none: "0",
    initial: "initial",
    xs: "0.25rem",
    sm: ".5rem",
    md: "1rem",
    lg: "1.125rem",
    xl: "1.25rem",
    xxl: "1.5rem",
    xxxl: "2rem",
    xxxxl: "4rem",
    xxxxxl: "6rem",
    xxxxxxl: "8rem",
    auto: "auto",
    full: "100%",
    fitContent: "fit-content",
  },
  radius: {
    sm: "2px",
    md: "6px",
    lg: "24px",
    full: "9999px",
  },
  zIndex: {
    auto: "auto",
    minus: "-1",
    "0": "0",
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
  },
  contentWidth: {
    xs: "50vw",
    sm: "65vw",
    md: "75vw",
    lg: "85vw",
    xl: "90vw",
    xxl: "95vw",
    full: "100vw",
  },
});

export const {
  font,
  fontSize,
  fontWeight,
  letterSpacing,
  lineHeight,
  spacing,
  radius,
  zIndex,
  contentWidth,
  rgb,
} = tokens;
